#-------------------------------
# General Site Settings

title: WnCC IIT Bombay
logo: logo.png
email: steve.fruits@email.com
phone: +880 2544 658 256
address: 125/A, CA Commercial Area, California, USA

menu:
- {name: About, link: '/about/'}
- {name: Blog, link: '/blog/'}
- {name: SoC, link: '/soc/'}
- {name: Contact, link: '/contact/'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Web And Coding Club

social:
- {icon: "ti-facebook", link: "#"}
- {icon: "ti-instagram", link: "#"}
- {icon: "ti-dribbble", link: "#"}
- {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
team:
  - title : "Jack Schenziwe"
    image : "assets/images/team/member-1.png"
    designation : "Project Manager"
    
  - title : "Julias Carlie"
    image : "assets/images/team/member-2.png"
    designation : "Web Developer"
    
  - title : "John Doe"
    image : "assets/images/team/member-3.png"
    designation : "Designer"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Web Design, color: '#fdb157', value: '90%'}
- {name: Logo Design, color: '#9473e6', value: '60%'}
- {name: After Effects, color: '#bdecf6', value: '80%'}
- {name: Web App, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Junior UX Designer, icon: 'icon-1.png', date: 'Jan 2007 - Feb 2009', organization: 'WEBEX'}
- {name: UX & UI Designer, icon: 'icon-2.png', date: 'Mar 2009 - Aug 2014', organization: 'AUGMEDIX'}
- {name: Senior UI Designer, icon: 'icon-3.png', date: 'Sep 2014 - Present', organization: 'THEMEFISHER'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Marters in UX Design, date: '2006', organization: 'Masassusets Institute of Technology'}
- {name: Honours in Fine Arts, date: '2004', organization: 'Harvard University'}
- {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
- {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}


#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: UI Design,
    icon: ti-palette,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    active: # Add true to select section
  }
- {
    name: UX Design,
    icon: ti-vector,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    active: true # Add true to select section
  }
- {
    name: Interaction Design,
    icon: ti-panel,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    active: # Add true to select section
  }



#-------------------------------
# SoC (Section and Page)

# About SoC Section
about-soc-what-is-soc:
  Seasons of Code is a programme launched by the WnCC, along the lines of GSoC without much greenery though. The incentive is similar to ITSP, based on the current form of it, the fundamental difference is that one can choose from the ideas offered by mentors who are senior undergrads, doctorate students or professors, and in some exceptional cases, startups. We plan to have a really long timeframe though, until the next winter extending this programme into a mentorship of sorts into the semester. It is not just about development by the way. We have some mentors ready to take up programmes regarding competitive coding and scientific computation too.
about-soc-why-participate:
  Seasons of Code gives you an amazing opportunity to learn and dive into coding under the mentorship of the best in our institute. Our list of projects gives you a chance to pick up and work on any topic you are enthusiastic about.


# SoC Home Section
soc-home-items:
  - image : "assets/images/soc/item-1.png"
    url: "#"
    
  - image : "assets/images/soc/item-2.png"
    url: "#"
    
  - image : "assets/images/soc/item-3.png"
    url: "#"
    
  - image : "assets/images/soc/item-4.png"
    url: "#"
    
  - image : "assets/images/soc/item-5.png"
    url: "#"


# SoC Page
soc-label:
- {
    title : "ML",
    type : "Machine Learning"
  }
- {
    title : "DEV",
    type : "Development"
  }
- {
    title : "IMAGE PROCESSING",
    type : "Image Processing"
  }
- {
    title : "DEEP LEARNING",
    type : "Deep Learning"
  }
- {
    title : "SIGNAL PROCESSING",
    type : "Signal Processing"
  }
- {
    title : "NEURAL NETWORKS",
    type : "Neural Networks"
  }
- {
    title : "WEB DEV",
    type : "Web Development"
  }
- {
    title : "ECONOMICS",
    type : "Economics"
  }
- {
    title : "NLP",
    type : "Natural Language Processing"
  }
- {
    title : "SPEECH RECOGNITION",
    type : "Speech Recognition"
  }
- {
    title : "GRAPHICS",
    type : "Graphics"
  }
- {
    title : "UI",
    type : "User Interface"
  }
- {
    title : "AR",
    type : "Augmented Reality"
  }
- {
    title : "CC",
    type : "Competitive Coding"
  }
- {
    title : "NETWORK SECURITY",
    type : "Network Security"
  }
- {
    title : "ANIMATION",
    type : "Animation"
  }
- {
    title : "AI",
    type : "Artificial Intelligence"
  }
- {
    title : "DATA SCIENCE",
    type : "Data Science"
  }


soc-items:
  - title : "Why The Hype Around GANs"
    image : "assets/images/soc/item-1.png"
    url: "https://www.wncc-iitb.org/soc_projects/44-akshit-gan.html"
    soc-type:
     - type: "Machine Learning"

  - title : "3D reconstruction using 2D images"
    image : "assets/images/soc/item-2.png"
    url: "https://www.wncc-iitb.org/soc_projects/45-siddesh-3d-reconstruction.html"
    soc-type:
     - type: "Development"
     - type: "Image Processing"
     - type: "Machine Learning"

  - title : "Computer Vision Workbench"
    image : "assets/images/soc/item-3.png"
    url: "https://www.wncc-iitb.org/soc_projects/46-vishal-cv-workbench.html"
    soc-type:
     - type: "Development"
     - type: "Image Processing"
     - type: "Machine Learning"
     - type: "Deep Learning"

  - title : "3D Object Classification using Mesh Neural Network"
    image : "assets/images/soc/item-4.png"
    url: "https://www.wncc-iitb.org/soc_projects/47-sudhir-neural.html"
    soc-type:
     - type: "Machine Learning"     

  - title : "Lossless high entropy compression algorithm"
    image : "assets/images/soc/item-5.png"
    url: "#"
    soc-type:
     - type: "Machine Learning"
     - type: "Signal Processing"
     - type: "Neural Networks" 

  - title : "Tools for Web Development"
    image : "assets/images/soc/item-6.png"
    url: "https://www.wncc-iitb.org/soc_projects/50-pritam-kumar-webdev.html"
    soc-type:
     - type: "Web Development"

  - title : "ML GYM"
    image : "assets/images/soc/item-7.png"
    url: "https://www.wncc-iitb.org/soc_projects/49-lalit-mlgym.html"
    soc-type:
     - type: "Machine Learnins"

  - title : "Strategy Wars [Online]"
    image : "assets/images/soc/item-8.png"
    url: "https://www.wncc-iitb.org/soc_projects/51-dhairya-strategywars.html"
    soc-type:
     - type: "Development"
     - type: "Web Development"
     - type: "Economics"

  - title : "Super Shenron"
    image : "assets/images/soc/item-9.png"
    url: "https://www.wncc-iitb.org/soc_projects/55-bharti-supershenron.html"
    soc-type:
     - type: "Web Develppment"

  - title : "Gestures for 3D space"
    image : "assets/images/soc/item-10.gif"
    url: "https://www.wncc-iitb.org/soc_projects/56-pagar-gestures.html"
    soc-type:
     - type: "Image Processing"
     - type: "Machine Learning"
     - type: "Development"

  - title : "Food Recommendation through Machine Learning"
    image : "assets/images/soc/item-11.png"
    url: "https://www.wncc-iitb.org/soc_projects/52-anuj-food.html"
    soc-type:
     - type: "Development"          
     - type: "Machine Learning"
      
  - title : "Conversational Chatbot"
    image : "assets/images/soc/item-12.png"
    url: "https://www.wncc-iitb.org/soc_projects/53-Ishwaryaa-chatbot.html"
    soc-type:
     - type: "Development"
     - type: "Machine Learning"
     - type: "Natural Language Processing"
     - type: "Speech Recognition"  

  - title : "(Un)structured"
    image : "assets/images/soc/item-13.png"
    url: "https://www.wncc-iitb.org/soc_projects/57-gagan-unstructured.html"
    soc-type:
     - type: "Image Processing"
     - type: "Machine Learning"

  - title : "Road Network 3D Rendering using OpenGL"
    image : "assets/images/soc/item-14.png"
    url: "https://www.wncc-iitb.org/soc_projects/58-debabrata-road-net.html"
    soc-type:
     - type: "Graphics"
     - type: "User Interface"

  - title : "Virtual Keyboard"
    image : "assets/images/soc/item-15.png"
    url: "https://www.wncc-iitb.org/soc_projects/54-manan-keyboard.html"
    soc-type:
     - type: "Augmented Reality"

  - title : "Introduction to Kaggle and Machine Learning"
    image : "assets/images/soc/item-16.png"
    url: "https://www.wncc-iitb.org/soc_projects/60-yash-kaggle.html"
    soc-type:
     - type: "Machine Learning"

  - title : "Krittika Website"
    image : "assets/images/soc/item-17.png"
    url: "https://www.wncc-iitb.org/soc_projects/62-chaitanya-krittika.html"
    soc-type:
     - type: "Web Development"

  - title : "Competitive coding"
    image : "assets/images/soc/item-18.png"
    url: "https://www.wncc-iitb.org/soc_projects/43-pratyush-competitive-coding.html"
    soc-type:
     - type: "Competitive Coding"  

  - title : "Planet/Atmosphere Renderer using OpenGL"
    image : "assets/images/soc/item-19.png"
    url: "https://www.wncc-iitb.org/soc_projects/64-rwitaban-computer-graphics.html"
    soc-type:
     - type: "Graphics"   

  - title : "Intrusion Detection system"
    image : "assets/images/soc/item-20.png"
    url: "https://www.wncc-iitb.org/soc_projects/42-rahul-intrusion-detection.html"
    soc-type:
     - type: "Machine Learning"
     - type: "Network Security"

  - title : "Rubik's cube solver"
    image : "assets/images/soc/item-21.png"
    url: "https://www.wncc-iitb.org/soc_projects/63-chaitanya-rubik-solver.html"
    soc-type:
     - type: "Development"
     - type: "Image Processing"
     - type: "Machine Learning"

  - title : "L.A.M.A. AI using Reinforcement Learning"
    image : "assets/images/soc/item-22.png"
    url: "https://www.wncc-iitb.org/soc_projects/41-cheeku-lama-ai.html"
    soc-type:
     - type: "Machine Learning"
     - type: "Development"

  - title : "Face Recognition using Statistics"
    image : "assets/images/soc/item-23.png"
    url: "https://www.wncc-iitb.org/soc_projects/59-shreya-face-recognition.html"
    soc-type:
     - type: "Machine Learning"

  - title : "Tinkerersâ€™ Laboratory Website"
    image : "assets/images/soc/item-24.png"
    url: "https://www.wncc-iitb.org/soc_projects/67-vivek-saurabh-verma-TL-website.html"
    soc-type:
     - type: "Web Development"

  - title : "Graphic Intensive MUSIC APP"
    image : "assets/images/soc/item-25.png"
    url: "https://www.wncc-iitb.org/soc_projects/68-sudanshu-sahil-Graphic-Intensive-Music-App.html"
    soc-type:
     - type: "Graphics"
     - type: "Development" 

  - title : "KontaKt App"
    image : "assets/images/soc/item-26.png"
    url: "https://www.wncc-iitb.org/soc_projects/66-prabhat-KontaKt-app.html"
    soc-type:
     - type: "Development"
     - type: "Web Development"
     - type: "Machine Learning"  

  - title : "Pool It!"
    image : "assets/images/soc/item-27.png"
    url: "https://www.wncc-iitb.org/soc_projects/69-aman-poolit.html"
    soc-type:
     - type: "Development"
     - type: "Web Development"    

  - title : "Digital Depth Perception"
    image : "assets/images/soc/item-28.png"
    url: "https://www.wncc-iitb.org/soc_projects/65-divyansh-depth.html"
    soc-type:
     - type: "Image Processing" 

  - title : "Insti Buddy"
    image : "assets/images/soc/item-29.png"
    url: "https://www.wncc-iitb.org/soc_projects/70-rishabh-instibuddy.html"
    soc-type:
     - type: "Development"
     - type: "Web Development"  

  - title : "Intelligent agents"
    image : "assets/images/soc/item-30.png"
    url: "https://www.wncc-iitb.org/soc_projects/71-sanjeev-intelligent.html"
    soc-type:
     - type: "Artificial Intelligence"
     - type: "Data Science" 

#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation : "CEO, Funder"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: steve.fruits@email.com